 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/template/audience_documents", type: :request do
  # Template::AudienceDocument. As you add validations to Template::AudienceDocument, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Template::AudienceDocument.create! valid_attributes
      get template_audience_documents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      audience_document = Template::AudienceDocument.create! valid_attributes
      get template_audience_document_url(template_audience_document)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_template_audience_document_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      audience_document = Template::AudienceDocument.create! valid_attributes
      get edit_template_audience_document_url(template_audience_document)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Template::AudienceDocument" do
        expect {
          post template_audience_documents_url, params: { template_audience_document: valid_attributes }
        }.to change(Template::AudienceDocument, :count).by(1)
      end

      it "redirects to the created template_audience_document" do
        post template_audience_documents_url, params: { template_audience_document: valid_attributes }
        expect(response).to redirect_to(template_audience_document_url(@template_audience_document))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Template::AudienceDocument" do
        expect {
          post template_audience_documents_url, params: { template_audience_document: invalid_attributes }
        }.to change(Template::AudienceDocument, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post template_audience_documents_url, params: { template_audience_document: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested template_audience_document" do
        audience_document = Template::AudienceDocument.create! valid_attributes
        patch template_audience_document_url(template_audience_document), params: { template_audience_document: new_attributes }
        audience_document.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the template_audience_document" do
        audience_document = Template::AudienceDocument.create! valid_attributes
        patch template_audience_document_url(template_audience_document), params: { template_audience_document: new_attributes }
        audience_document.reload
        expect(response).to redirect_to(template_audience_document_url(audience_document))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        audience_document = Template::AudienceDocument.create! valid_attributes
        patch template_audience_document_url(template_audience_document), params: { template_audience_document: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested template_audience_document" do
      audience_document = Template::AudienceDocument.create! valid_attributes
      expect {
        delete template_audience_document_url(template_audience_document)
      }.to change(Template::AudienceDocument, :count).by(-1)
    end

    it "redirects to the template_audience_documents list" do
      audience_document = Template::AudienceDocument.create! valid_attributes
      delete template_audience_document_url(template_audience_document)
      expect(response).to redirect_to(template_audience_documents_url)
    end
  end
end
