require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/descriptor/activities", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Descriptor::Activity. As you add validations to Descriptor::Activity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Descriptor::Activity.create! valid_attributes
      get descriptor_activities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      activity = Descriptor::Activity.create! valid_attributes
      get descriptor_activity_url(activity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_descriptor_activity_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      activity = Descriptor::Activity.create! valid_attributes
      get edit_descriptor_activity_url(activity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Descriptor::Activity" do
        expect {
          post descriptor_activities_url, params: { descriptor_activity: valid_attributes }
        }.to change(Descriptor::Activity, :count).by(1)
      end

      it "redirects to the created descriptor_activity" do
        post descriptor_activities_url, params: { descriptor_activity: valid_attributes }
        expect(response).to redirect_to(descriptor_activity_url(Descriptor::Activity.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Descriptor::Activity" do
        expect {
          post descriptor_activities_url, params: { descriptor_activity: invalid_attributes }
        }.to change(Descriptor::Activity, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post descriptor_activities_url, params: { descriptor_activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested descriptor_activity" do
        activity = Descriptor::Activity.create! valid_attributes
        patch descriptor_activity_url(activity), params: { descriptor_activity: new_attributes }
        activity.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the descriptor_activity" do
        activity = Descriptor::Activity.create! valid_attributes
        patch descriptor_activity_url(activity), params: { descriptor_activity: new_attributes }
        activity.reload
        expect(response).to redirect_to(descriptor_activity_url(activity))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        activity = Descriptor::Activity.create! valid_attributes
        patch descriptor_activity_url(activity), params: { descriptor_activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested descriptor_activity" do
      activity = Descriptor::Activity.create! valid_attributes
      expect {
        delete descriptor_activity_url(activity)
      }.to change(Descriptor::Activity, :count).by(-1)
    end

    it "redirects to the descriptor_activities list" do
      activity = Descriptor::Activity.create! valid_attributes
      delete descriptor_activity_url(activity)
      expect(response).to redirect_to(descriptor_activities_url)
    end
  end
end
