require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/descriptor/privileges", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Descriptor::Privilege. As you add validations to Descriptor::Privilege, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Descriptor::Privilege.create! valid_attributes
      get descriptor_privileges_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      privilege = Descriptor::Privilege.create! valid_attributes
      get descriptor_privilege_url(privilege)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_descriptor_privilege_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      privilege = Descriptor::Privilege.create! valid_attributes
      get edit_descriptor_privilege_url(privilege)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Descriptor::Privilege" do
        expect {
          post descriptor_privileges_url, params: { descriptor_privilege: valid_attributes }
        }.to change(Descriptor::Privilege, :count).by(1)
      end

      it "redirects to the created descriptor_privilege" do
        post descriptor_privileges_url, params: { descriptor_privilege: valid_attributes }
        expect(response).to redirect_to(descriptor_privilege_url(Descriptor::Privilege.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Descriptor::Privilege" do
        expect {
          post descriptor_privileges_url, params: { descriptor_privilege: invalid_attributes }
        }.to change(Descriptor::Privilege, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post descriptor_privileges_url, params: { descriptor_privilege: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested descriptor_privilege" do
        privilege = Descriptor::Privilege.create! valid_attributes
        patch descriptor_privilege_url(privilege), params: { descriptor_privilege: new_attributes }
        privilege.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the descriptor_privilege" do
        privilege = Descriptor::Privilege.create! valid_attributes
        patch descriptor_privilege_url(privilege), params: { descriptor_privilege: new_attributes }
        privilege.reload
        expect(response).to redirect_to(descriptor_privilege_url(privilege))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        privilege = Descriptor::Privilege.create! valid_attributes
        patch descriptor_privilege_url(privilege), params: { descriptor_privilege: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested descriptor_privilege" do
      privilege = Descriptor::Privilege.create! valid_attributes
      expect {
        delete descriptor_privilege_url(privilege)
      }.to change(Descriptor::Privilege, :count).by(-1)
    end

    it "redirects to the descriptor_privileges list" do
      privilege = Descriptor::Privilege.create! valid_attributes
      delete descriptor_privilege_url(privilege)
      expect(response).to redirect_to(descriptor_privileges_url)
    end
  end
end
