version: 2
jobs:
    build:
        working_directory: ~/my-app
        docker:
            - image: circleci/ruby:2.6.4-node-browsers
        steps:
            - checkout

            - run:
                name: Which bundler?
                command: bundle -v
