version: 2
jobs:
    build:
        working_directory: ~/my-app
        docker:
            - image: circleci/ruby:2.7.0
              environment:
                PGHOST: 127.0.0.1
                PGUSER: root
                PGDB: leslicloud_test
                PGPASSWORD: "leslicloud_test"
                RAILS_ENV: test
            - image: circleci/postgres:11.5
              environment:
                POSTGRES_USER: root
                POSTGRES_DB: leslicloud_test
                POSTGRES_PASSWORD: "leslicloud_test"
                RAILS_ENV: test
        steps:
            - checkout
            - run:
                name: Upgrade bundler
                command: gem install bundler
            - run:
                name: Check bundler version
                command: bundle -v
            - restore_cache:
                keys:
                    - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
                    - rails-demo-bundle-v2-
            - run:
                name: Bundle Install
                command: |
                    gem update --system
                    bundle config set path 'vendor/bundle'
                    bundle check || bundle install
            - save_cache:
                key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
            - run:
                name: Wait for DB
                command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run:
                name: Database setup 
                command: bin/rails db:create db:schema:load --trace 

            - run:
                name: Run rspec tests 
                command: rspec spec
