version: 2
jobs:
    build:
        working_directory: ~/my-app
        docker:
            - image: circleci/ruby:2.6.4-stretch
             environment:
                PGHOST: localhost
                PGUSER: my-app
                RAILS_ENV: test
            - image: circleci/postgres:11.5
        steps:
            - checkout
            - run:
                name: Upgrade bundler
                command: gem install bundler
            - run:
                name: Check bundler version
                command: bundle -v
