version: 2.1 

orbs:
    ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs: 
    build: 
        docker:
            - image: circleci/ruby:2.6.3-stretch-node
                environment:
                    DATABASE_URL: 'postgresql://root@localhost/circle_test'
            - image: 'circleci/postgres:9.6.5-alpine-ram'
        steps: 
            - checkout

            # Which version of bundler?
            - run:
                name: Which bundler?
                command: bundle -v

            # Restore bundle cache
            # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
            - restore_cache:
                keys:
                    - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
                    - rails-demo-bundle-v2-

            - run: # Install Ruby dependencies
                name: Bundle Install
                command: bundle check --path vendor/bundle || bundle install --deployment

            # Store bundle cache for Ruby dependencies
            - save_cache:
                key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle

            - run:
                name: Wait for DB
                command: dockerize -wait tcp://localhost:5432 -timeout 1m

            - run:
                name: Database setup
                command: bin/rails db:schema:load --trace

            - run:
                name: Run rspec in parallel
                command: rspec spec

            # Save test results for timing analysis
            - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
                path: test_results
