version: 2
jobs:
    build:
        working_directory: ~/my-app
        docker:
            - image: circleci/ruby:2.6.4-stretch
            - image: circleci/postgres:11.5
        environment:
            PGHOST: localhost
            PGUSER: my-app
            RAILS_ENV: test
        steps:
            - checkout
            - run:
                name: Upgrade bundler
                command: gem install bundler
            - run:
                name: Check bundler version
                command: bundle -v
            - restore_cache:
                keys:
                    - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
                    - rails-demo-bundle-v2-
            - run:
                name: Bundle Install
                command: |
                    gem update --system
                    bundle config set path 'vendor/bundle'
                    bundle check || bundle install --deployment
