version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4
    steps:
      - checkout
      - run: echo "A first hello"
      - run: ssh -oStrictHostKeyChecking=no -v $SERVER_USER@$SERVER_ADDRESS 'cd /var/www/lesli.cloud && git pull github master'
