 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role/activities", type: :request do
  # Role::Activity. As you add validations to Role::Activity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Role::Activity.create! valid_attributes
      get role_activities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      activity = Role::Activity.create! valid_attributes
      get role_activity_url(role_activity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_role_activity_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      activity = Role::Activity.create! valid_attributes
      get edit_role_activity_url(role_activity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Role::Activity" do
        expect {
          post role_activities_url, params: { role_activity: valid_attributes }
        }.to change(Role::Activity, :count).by(1)
      end

      it "redirects to the created role_activity" do
        post role_activities_url, params: { role_activity: valid_attributes }
        expect(response).to redirect_to(role_activity_url(@role_activity))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Role::Activity" do
        expect {
          post role_activities_url, params: { role_activity: invalid_attributes }
        }.to change(Role::Activity, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post role_activities_url, params: { role_activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_activity" do
        activity = Role::Activity.create! valid_attributes
        patch role_activity_url(role_activity), params: { role_activity: new_attributes }
        activity.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_activity" do
        activity = Role::Activity.create! valid_attributes
        patch role_activity_url(role_activity), params: { role_activity: new_attributes }
        activity.reload
        expect(response).to redirect_to(role_activity_url(activity))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        activity = Role::Activity.create! valid_attributes
        patch role_activity_url(role_activity), params: { role_activity: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_activity" do
      activity = Role::Activity.create! valid_attributes
      expect {
        delete role_activity_url(role_activity)
      }.to change(Role::Activity, :count).by(-1)
    end

    it "redirects to the role_activities list" do
      activity = Role::Activity.create! valid_attributes
      delete role_activity_url(role_activity)
      expect(response).to redirect_to(role_activities_url)
    end
  end
end
