 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role/details", type: :request do
  # Role::Detail. As you add validations to Role::Detail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Role::Detail.create! valid_attributes
      get role_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      detail = Role::Detail.create! valid_attributes
      get role_detail_url(role_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_role_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      detail = Role::Detail.create! valid_attributes
      get edit_role_detail_url(role_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Role::Detail" do
        expect {
          post role_details_url, params: { role_detail: valid_attributes }
        }.to change(Role::Detail, :count).by(1)
      end

      it "redirects to the created role_detail" do
        post role_details_url, params: { role_detail: valid_attributes }
        expect(response).to redirect_to(role_detail_url(@role_detail))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Role::Detail" do
        expect {
          post role_details_url, params: { role_detail: invalid_attributes }
        }.to change(Role::Detail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post role_details_url, params: { role_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_detail" do
        detail = Role::Detail.create! valid_attributes
        patch role_detail_url(role_detail), params: { role_detail: new_attributes }
        detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_detail" do
        detail = Role::Detail.create! valid_attributes
        patch role_detail_url(role_detail), params: { role_detail: new_attributes }
        detail.reload
        expect(response).to redirect_to(role_detail_url(detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        detail = Role::Detail.create! valid_attributes
        patch role_detail_url(role_detail), params: { role_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_detail" do
      detail = Role::Detail.create! valid_attributes
      expect {
        delete role_detail_url(role_detail)
      }.to change(Role::Detail, :count).by(-1)
    end

    it "redirects to the role_details list" do
      detail = Role::Detail.create! valid_attributes
      delete role_detail_url(role_detail)
      expect(response).to redirect_to(role_details_url)
    end
  end
end
