 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role/overrides", type: :request do
  # Role::Override. As you add validations to Role::Override, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Role::Override.create! valid_attributes
      get role_overrides_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      override = Role::Override.create! valid_attributes
      get role_override_url(role_override)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_role_override_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      override = Role::Override.create! valid_attributes
      get edit_role_override_url(role_override)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Role::Override" do
        expect {
          post role_overrides_url, params: { role_override: valid_attributes }
        }.to change(Role::Override, :count).by(1)
      end

      it "redirects to the created role_override" do
        post role_overrides_url, params: { role_override: valid_attributes }
        expect(response).to redirect_to(role_override_url(@role_override))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Role::Override" do
        expect {
          post role_overrides_url, params: { role_override: invalid_attributes }
        }.to change(Role::Override, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post role_overrides_url, params: { role_override: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_override" do
        override = Role::Override.create! valid_attributes
        patch role_override_url(role_override), params: { role_override: new_attributes }
        override.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_override" do
        override = Role::Override.create! valid_attributes
        patch role_override_url(role_override), params: { role_override: new_attributes }
        override.reload
        expect(response).to redirect_to(role_override_url(override))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        override = Role::Override.create! valid_attributes
        patch role_override_url(role_override), params: { role_override: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_override" do
      override = Role::Override.create! valid_attributes
      expect {
        delete role_override_url(role_override)
      }.to change(Role::Override, :count).by(-1)
    end

    it "redirects to the role_overrides list" do
      override = Role::Override.create! valid_attributes
      delete role_override_url(role_override)
      expect(response).to redirect_to(role_overrides_url)
    end
  end
end
