 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role/privilege_groups", type: :request do
  # Role::PrivilegeGroup. As you add validations to Role::PrivilegeGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Role::PrivilegeGroup.create! valid_attributes
      get role_privilege_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      privilege_group = Role::PrivilegeGroup.create! valid_attributes
      get role_privilege_group_url(role_privilege_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    # it "renders a successful response" do
    #   get new_role_privilege_group_url
    #   expect(response).to be_successful
    # end
  end

  describe "GET /edit" do
    it "render a successful response" do
      privilege_group = Role::PrivilegeGroup.create! valid_attributes
      get edit_role_privilege_group_url(role_privilege_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    # context "with valid parameters" do
    #   it "creates a new Role::PrivilegeGroup" do
    #     expect {
    #       post role_privilege_groups_url, params: { role_privilege_group: valid_attributes }
    #     }.to change(Role::PrivilegeGroup, :count).by(1)
    #   end

    #   it "redirects to the created role_privilege_group" do
    #     post role_privilege_groups_url, params: { role_privilege_group: valid_attributes }
    #     expect(response).to redirect_to(role_privilege_group_url(@role_privilege_group))
    #   end
    # end

    # context "with invalid parameters" do
    #   it "does not create a new Role::PrivilegeGroup" do
    #     expect {
    #       post role_privilege_groups_url, params: { role_privilege_group: invalid_attributes }
    #     }.to change(Role::PrivilegeGroup, :count).by(0)
    #   end

    #   it "renders a successful response (i.e. to display the 'new' template)" do
    #     post role_privilege_groups_url, params: { role_privilege_group: invalid_attributes }
    #     expect(response).to be_successful
    #   end
    # end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_privilege_group" do
        privilege_group = Role::PrivilegeGroup.create! valid_attributes
        patch role_privilege_group_url(role_privilege_group), params: { role_privilege_group: new_attributes }
        privilege_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_privilege_group" do
        privilege_group = Role::PrivilegeGroup.create! valid_attributes
        patch role_privilege_group_url(role_privilege_group), params: { role_privilege_group: new_attributes }
        privilege_group.reload
        expect(response).to redirect_to(role_privilege_group_url(privilege_group))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        privilege_group = Role::PrivilegeGroup.create! valid_attributes
        patch role_privilege_group_url(role_privilege_group), params: { role_privilege_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_privilege_group" do
      privilege_group = Role::PrivilegeGroup.create! valid_attributes
      expect {
        delete role_privilege_group_url(role_privilege_group)
      }.to change(Role::PrivilegeGroup, :count).by(-1)
    end

    it "redirects to the role_privilege_groups list" do
      privilege_group = Role::PrivilegeGroup.create! valid_attributes
      delete role_privilege_group_url(role_privilege_group)
      expect(response).to redirect_to(role_privilege_groups_url)
    end
  end
end
