 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/role/privileges", type: :request do
  # Role::Privilege. As you add validations to Role::Privilege, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Role::Privilege.create! valid_attributes
      get role_privileges_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      privilege = Role::Privilege.create! valid_attributes
      get role_privilege_url(role_privilege)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_role_privilege_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      privilege = Role::Privilege.create! valid_attributes
      get edit_role_privilege_url(role_privilege)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Role::Privilege" do
        expect {
          post role_privileges_url, params: { role_privilege: valid_attributes }
        }.to change(Role::Privilege, :count).by(1)
      end

      it "redirects to the created role_privilege" do
        post role_privileges_url, params: { role_privilege: valid_attributes }
        expect(response).to redirect_to(role_privilege_url(@role_privilege))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Role::Privilege" do
        expect {
          post role_privileges_url, params: { role_privilege: invalid_attributes }
        }.to change(Role::Privilege, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post role_privileges_url, params: { role_privilege: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested role_privilege" do
        privilege = Role::Privilege.create! valid_attributes
        patch role_privilege_url(role_privilege), params: { role_privilege: new_attributes }
        privilege.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the role_privilege" do
        privilege = Role::Privilege.create! valid_attributes
        patch role_privilege_url(role_privilege), params: { role_privilege: new_attributes }
        privilege.reload
        expect(response).to redirect_to(role_privilege_url(privilege))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        privilege = Role::Privilege.create! valid_attributes
        patch role_privilege_url(role_privilege), params: { role_privilege: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested role_privilege" do
      privilege = Role::Privilege.create! valid_attributes
      expect {
        delete role_privilege_url(role_privilege)
      }.to change(Role::Privilege, :count).by(-1)
    end

    it "redirects to the role_privileges list" do
      privilege = Role::Privilege.create! valid_attributes
      delete role_privilege_url(role_privilege)
      expect(response).to redirect_to(role_privileges_url)
    end
  end
end
