require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/descriptors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Descriptor. As you add validations to Descriptor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Descriptor.create! valid_attributes
      get descriptors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      descriptor = Descriptor.create! valid_attributes
      get descriptor_url(descriptor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_descriptor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      descriptor = Descriptor.create! valid_attributes
      get edit_descriptor_url(descriptor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Descriptor" do
        expect {
          post descriptors_url, params: { descriptor: valid_attributes }
        }.to change(Descriptor, :count).by(1)
      end

      it "redirects to the created descriptor" do
        post descriptors_url, params: { descriptor: valid_attributes }
        expect(response).to redirect_to(descriptor_url(Descriptor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Descriptor" do
        expect {
          post descriptors_url, params: { descriptor: invalid_attributes }
        }.to change(Descriptor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post descriptors_url, params: { descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested descriptor" do
        descriptor = Descriptor.create! valid_attributes
        patch descriptor_url(descriptor), params: { descriptor: new_attributes }
        descriptor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the descriptor" do
        descriptor = Descriptor.create! valid_attributes
        patch descriptor_url(descriptor), params: { descriptor: new_attributes }
        descriptor.reload
        expect(response).to redirect_to(descriptor_url(descriptor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        descriptor = Descriptor.create! valid_attributes
        patch descriptor_url(descriptor), params: { descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested descriptor" do
      descriptor = Descriptor.create! valid_attributes
      expect {
        delete descriptor_url(descriptor)
      }.to change(Descriptor, :count).by(-1)
    end

    it "redirects to the descriptors list" do
      descriptor = Descriptor.create! valid_attributes
      delete descriptor_url(descriptor)
      expect(response).to redirect_to(descriptors_url)
    end
  end
end
