 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_controllers", type: :request do
  # SystemController. As you add validations to SystemController, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemController.create! valid_attributes
      get system_controllers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_controller = SystemController.create! valid_attributes
      get system_controller_url(system_controller)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      system_controller = SystemController.create! valid_attributes
      get edit_system_controller_url(system_controller)
      expect(response).to be_successful
    end
  end
end
