require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_descriptors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SystemDescriptor. As you add validations to SystemDescriptor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemDescriptor.create! valid_attributes
      get system_descriptors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_descriptor = SystemDescriptor.create! valid_attributes
      get system_descriptor_url(system_descriptor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_descriptor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      system_descriptor = SystemDescriptor.create! valid_attributes
      get edit_system_descriptor_url(system_descriptor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemDescriptor" do
        expect {
          post system_descriptors_url, params: { system_descriptor: valid_attributes }
        }.to change(SystemDescriptor, :count).by(1)
      end

      it "redirects to the created system_descriptor" do
        post system_descriptors_url, params: { system_descriptor: valid_attributes }
        expect(response).to redirect_to(system_descriptor_url(SystemDescriptor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemDescriptor" do
        expect {
          post system_descriptors_url, params: { system_descriptor: invalid_attributes }
        }.to change(SystemDescriptor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post system_descriptors_url, params: { system_descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_descriptor" do
        system_descriptor = SystemDescriptor.create! valid_attributes
        patch system_descriptor_url(system_descriptor), params: { system_descriptor: new_attributes }
        system_descriptor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_descriptor" do
        system_descriptor = SystemDescriptor.create! valid_attributes
        patch system_descriptor_url(system_descriptor), params: { system_descriptor: new_attributes }
        system_descriptor.reload
        expect(response).to redirect_to(system_descriptor_url(system_descriptor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        system_descriptor = SystemDescriptor.create! valid_attributes
        patch system_descriptor_url(system_descriptor), params: { system_descriptor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_descriptor" do
      system_descriptor = SystemDescriptor.create! valid_attributes
      expect {
        delete system_descriptor_url(system_descriptor)
      }.to change(SystemDescriptor, :count).by(-1)
    end

    it "redirects to the system_descriptors list" do
      system_descriptor = SystemDescriptor.create! valid_attributes
      delete system_descriptor_url(system_descriptor)
      expect(response).to redirect_to(system_descriptors_url)
    end
  end
end
