 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_controllers", type: :request do
  # SystemController. As you add validations to SystemController, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemController.create! valid_attributes
      get system_controllers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_controller = SystemController.create! valid_attributes
      get system_controller_url(system_controller)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_controller_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      system_controller = SystemController.create! valid_attributes
      get edit_system_controller_url(system_controller)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemController" do
        expect {
          post system_controllers_url, params: { system_controller: valid_attributes }
        }.to change(SystemController, :count).by(1)
      end

      it "redirects to the created system_controller" do
        post system_controllers_url, params: { system_controller: valid_attributes }
        expect(response).to redirect_to(system_controller_url(SystemController.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemController" do
        expect {
          post system_controllers_url, params: { system_controller: invalid_attributes }
        }.to change(SystemController, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post system_controllers_url, params: { system_controller: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_controller" do
        system_controller = SystemController.create! valid_attributes
        patch system_controller_url(system_controller), params: { system_controller: new_attributes }
        system_controller.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_controller" do
        system_controller = SystemController.create! valid_attributes
        patch system_controller_url(system_controller), params: { system_controller: new_attributes }
        system_controller.reload
        expect(response).to redirect_to(system_controller_url(system_controller))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        system_controller = SystemController.create! valid_attributes
        patch system_controller_url(system_controller), params: { system_controller: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_controller" do
      system_controller = SystemController.create! valid_attributes
      expect {
        delete system_controller_url(system_controller)
      }.to change(SystemController, :count).by(-1)
    end

    it "redirects to the system_controllers list" do
      system_controller = SystemController.create! valid_attributes
      delete system_controller_url(system_controller)
      expect(response).to redirect_to(system_controllers_url)
    end
  end
end
