development:
    adapter: postgresql
    encoding: unicode
    reconnect: false
    database: leslicloud_development
    pool: 30
    username: lesli_cloud
    password: lesli_cloud
    host: 127.0.0.1
    migrations_paths:
        - "db/migrate"
        - "engines/CloudPanel/db/migrate"
        - "engines/CloudTeam/db/migrate"
test:
    adapter: postgresql
    encoding: unicode
    reconnect: false
    database: leslicloud_test
    pool: 30
    username: lesli_cloud
    password: lesli_cloud
    host: 127.0.0.1
    migrations_paths:
        - "db/migrate"
        - "engines/CloudPanel/db/migrate"
        - "engines/CloudTeam/db/migrate"
