development:
  adapter: postgresql
  database: leslicloud_development
  username: lesli_cloud
  password: lesli_cloud
  host: localhost

test:
  database: leslicloud_test

production:
  database: leslicloud_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
