# Lesli
# For more information read the license file including with this software.

common: &common
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false

development:
    <<: *common
    database: <%= Rails.application.credentials.dig(:db, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :password) %>
    port: <%= Rails.application.credentials.dig(:db, :port) || 5432 %>

test:
    <<: *common
    database: <%= Rails.application.credentials.dig(:db, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :password) %>
    port: <%= Rails.application.credentials.dig(:db, :port) || 5432 %>

production:
    <<: *common
    port: <%= Rails.application.credentials.dig(:db, :port) %>
    host: <%= Rails.application.credentials.dig(:db, :host) %>
    database: <%= Rails.application.credentials.dig(:db, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :password) %>

production_dev:
    <<: *common
    database: <%= Rails.application.credentials.dig(:db, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :password) %>
