common: &common
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false
    migrations_paths:
        - "db/migrate"
        - "engines/CloudTeam/db/migrate"

development:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

staging:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

production:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

