common: &common
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false

development:
    core: 
        <<: *common
        database: "leslicloud_core_development"
        username: <%= Rails.application.credentials.db[:username] %>
        password: <%= Rails.application.credentials.db[:password] %>
        migrations_paths: "db/migrate/core"
    core_replica: 
        <<: *common
        database: "leslicloud_core_development"
        username: <%= Rails.application.credentials.db[:username] %>
        password: <%= Rails.application.credentials.db[:password] %>
        replica: true
    babel: 
        <<: *common
        database: "leslicloud_babel_development"
        username: <%= Rails.application.credentials.db[:username] %>
        password: <%= Rails.application.credentials.db[:password] %>
        migrations_paths: "engines/CloudBabel/db/migrate/babel"
    babel_replica: 
        <<: *common
        database: "leslicloud_babel_development"
        username: <%= Rails.application.credentials.db[:username] %>
        password: <%= Rails.application.credentials.db[:password] %>
        replica: true
