development:
    core: 
        pool: 30
        host: 127.0.0.1
        adapter: postgresql
        encoding: unicode
        reconnect: false
        database: leslicloud_core_development
        username: <username>
        password: <password>
        migrations_paths:
            - "db/migrate"
    panel: 
        pool: 30
        host: 127.0.0.1
        adapter: postgresql
        encoding: unicode
        reconnect: false
        database: leslicloud_panel_development
        username: <username>
        password: <password>
        migrations_paths:
            - "engines/CloudPanel/db/migrate"
    team: 
        pool: 30
        host: 127.0.0.1
        adapter: postgresql
        encoding: unicode
        reconnect: false
        database: leslicloud_team_development
        username: <username>
        password: <password>
        migrations_paths:
            - "engines/CloudTeam/db/migrate"
