common: &common
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false

development:
    core: 
        <<: *common
        database: <%= Rails.application.credentials.db[:database] %>
        username: <%= Rails.application.credentials.db[:username] %>
        password: <%= Rails.application.credentials.db[:password] %>
