common: &common
    pool: 30
    host: 127.0.0.1
    adapter: postgresql
    encoding: unicode
    reconnect: false

development:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

test:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

production:
    <<: *common
    database: <%= Rails.application.credentials.db[:database] %>
    username: <%= Rails.application.credentials.db[:username] %>
    password: <%= Rails.application.credentials.db[:password] %>

