development:
    i18n_default_locale: en
    devise_mailer_sender: "dev@lesli.cloud"
    action_mailer:
        asset_host: "http://0.0.0.0:3000"
        default_options_from: "dev@lesli.tech"
        default_url_options_host: "http://0.0.0.0:3000"

production:
    i18n_default_locale: en
    devise_mailer_sender: "dev@lesli.cloud"
    action_mailer:
        asset_host: "http://0.0.0.0:3000"
        default_options_from: "dev@lesli.tech"
        default_url_options_host: "http://0.0.0.0:3000"
