require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user/describers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # User::Describer. As you add validations to User::Describer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      User::Describer.create! valid_attributes
      get user_describers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      describer = User::Describer.create! valid_attributes
      get user_describer_url(describer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_describer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      describer = User::Describer.create! valid_attributes
      get edit_user_describer_url(describer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User::Describer" do
        expect {
          post user_describers_url, params: { user_describer: valid_attributes }
        }.to change(User::Describer, :count).by(1)
      end

      it "redirects to the created user_describer" do
        post user_describers_url, params: { user_describer: valid_attributes }
        expect(response).to redirect_to(user_describer_url(User::Describer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new User::Describer" do
        expect {
          post user_describers_url, params: { user_describer: invalid_attributes }
        }.to change(User::Describer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_describers_url, params: { user_describer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_describer" do
        describer = User::Describer.create! valid_attributes
        patch user_describer_url(describer), params: { user_describer: new_attributes }
        describer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_describer" do
        describer = User::Describer.create! valid_attributes
        patch user_describer_url(describer), params: { user_describer: new_attributes }
        describer.reload
        expect(response).to redirect_to(user_describer_url(describer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        describer = User::Describer.create! valid_attributes
        patch user_describer_url(describer), params: { user_describer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_describer" do
      describer = User::Describer.create! valid_attributes
      expect {
        delete user_describer_url(describer)
      }.to change(User::Describer, :count).by(-1)
    end

    it "redirects to the user_describers list" do
      describer = User::Describer.create! valid_attributes
      delete user_describer_url(describer)
      expect(response).to redirect_to(user_describers_url)
    end
  end
end
