require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/account/issues", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Account::Issue. As you add validations to Account::Issue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Account::Issue.create! valid_attributes
      get account_issues_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      issue = Account::Issue.create! valid_attributes
      get account_issue_url(issue)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_account_issue_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      issue = Account::Issue.create! valid_attributes
      get edit_account_issue_url(issue)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Account::Issue" do
        expect {
          post account_issues_url, params: { account_issue: valid_attributes }
        }.to change(Account::Issue, :count).by(1)
      end

      it "redirects to the created account_issue" do
        post account_issues_url, params: { account_issue: valid_attributes }
        expect(response).to redirect_to(account_issue_url(Account::Issue.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Account::Issue" do
        expect {
          post account_issues_url, params: { account_issue: invalid_attributes }
        }.to change(Account::Issue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post account_issues_url, params: { account_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested account_issue" do
        issue = Account::Issue.create! valid_attributes
        patch account_issue_url(issue), params: { account_issue: new_attributes }
        issue.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the account_issue" do
        issue = Account::Issue.create! valid_attributes
        patch account_issue_url(issue), params: { account_issue: new_attributes }
        issue.reload
        expect(response).to redirect_to(account_issue_url(issue))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        issue = Account::Issue.create! valid_attributes
        patch account_issue_url(issue), params: { account_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested account_issue" do
      issue = Account::Issue.create! valid_attributes
      expect {
        delete account_issue_url(issue)
      }.to change(Account::Issue, :count).by(-1)
    end

    it "redirects to the account_issues list" do
      issue = Account::Issue.create! valid_attributes
      delete account_issue_url(issue)
      expect(response).to redirect_to(account_issues_url)
    end
  end
end
