# Continuous integration

name: CI

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  get_instances:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.request.outputs.response }}
    steps:
    - id: request
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://run.mocky.io/v3/eff4cbf2-2fb4-4b63-9f51-4b25001b7753'
        method: 'GET'
  test:
    needs: get_instances
    strategy:
      matrix: ${{fromJson(needs.get_instances.outputs.matrix)}}
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: leslicloud_test
          POSTGRES_DB: leslicloud_test
          POSTGRES_PASSWORD: "leslicloud_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Install dependencies
      run: |
        bundle config https://rubygems.pkg.github.com/leitfaden ${GEM_HOST_API_KEY}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        RAILS_ENV: test
        GEM_HOST_API_KEY: "sagastume:${{secrets.PAT_FOR_BUILD}}"
        LESLI_INSTANCE_NAME: ${{ matrix.name }}
        LESLI_INSTANCE_CODE: ${{ matrix.code }}
        LESLI_INSTANCE_VERSION: ${{ matrix.version }}
    - name: Setup test database
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle exec rails db:migrate
        bundle exec rake db:setup
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
    - name: Setup Babel
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle exec rake cloud_babel:sync
        bundle exec rake cloud_babel:rails
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
        LESLI_INSTANCE_NAME: ${{ matrix.name }}
        LESLI_INSTANCE_CODE: ${{ matrix.code }}
        LESLI_INSTANCE_VERSION: ${{ matrix.version }}
    - name: Run tests
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle exec rspec ./spec/controllers
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
        LESLI_INSTANCE_NAME: ${{ matrix.name }}
        LESLI_INSTANCE_CODE: ${{ matrix.code }}
        LESLI_INSTANCE_VERSION: ${{ matrix.version }}
