# Continuous integration

name: CI

on:
  pull_request:
    branches:
      - master
      - production

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: leslicloud_test
          POSTGRES_DB: leslicloud_test
          POSTGRES_PASSWORD: "leslicloud_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-core-gems-${{ hashFiles('./Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-core-gems-
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-core-node-${{ hashFiles('./package.json') }}
        restore-keys: |
          ${{ runner.os }}-core-node-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Install dependencies of Rails
      run: |
        bundle config https://rubygems.pkg.github.com/leitfaden ${GEM_HOST_API_KEY}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle list
      env:
        RAILS_ENV: test
        GEM_HOST_API_KEY: "sagastume:${{secrets.READ_GEM_BY_ACTIONS}}"
    - name: Core NPM install
      run: |
        npm install
    - name: Setup test database
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle list
        bundle exec rake db:drop
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:setup
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
    - name: Run Spec tests
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle exec rspec
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
    - name: Checkout LesliShield
      uses: actions/checkout@v2
      with:
        repository: leitfaden/LesliShield
        ref: master
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./LesliShield/
    - name: Setup test database
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle list
        bundle exec rake db:drop
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:setup
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
    - name: Run Rails
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle exec rails s
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.CORE_RAILS_MASTER_KEY_TEST }}
    - name: LesliShield NPM install
      run: |
        cd ./LesliShield/
        npm install
        cd ..
    - name: Run tests PlayWright
      run: |
        cd ./LesliShield/
        npm run test:gui:lesli
        cd ..
