# Continuous integration

name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  get_instances:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::${INSTANCES}"
      env:
        INSTANCES: "{\"instances\": [\"lesli\", \"leibrenten\"]}"
  test:
    needs: get_instances
    strategy:
      matrix: ${{fromJson(needs.get_instances.outputs.matrix)}}
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: leslicloud_test
          POSTGRES_DB: leslicloud_test
          POSTGRES_PASSWORD: "leslicloud_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Install dependencies
      run: |
        bundle config https://rubygems.pkg.github.com/leitfaden ${GEM_HOST_API_KEY}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        GEM_HOST_API_KEY: "sagastume:${{secrets.PAT_FOR_BUILD}}"
        LESLI_INSTANCE: ${{ matrix.instance }}
    - name: Run tests
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        COVERAGE=true bundle exec rake spec:controllers
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
        LESLI_INSTANCE: ${{ matrix.instance }}
