name: New tag for a version
on:
  push:
    branches:
      - production
jobs:
  version_tag:
    name: Version Tag
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout GitHub Actions Repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/github_actions
        ref: production
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./.github/
    - name: New tag version
      uses: ./.github/actions/git_tag_new_version
      id: bumVersion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
