name: New tag for a version
on:
  push:
    branches:
      - production
jobs:
  version_tag:
    name: Version Tag
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'release(gem):') && !contains(github.event.head_commit.message, 'assets(js):')"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
    - run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
    - name: Checkout GitHub Actions Repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/github_actions
        ref: production
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./.github/
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-lesli-core-${{ hashFiles('./package.json') }}
        restore-keys: |
          ${{ runner.os }}-lesli-core-
    - name: NPM install
      run: |
        npm install --prefix ./lib/vue2
    - name: Compile Js to Production
      run: |
        npm run webpack:production
    - name: Commit Compile js
      run: |
        git add ./app/assets/
        git commit -m "assets(js): Compile Js to Production"
        git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF##*/}
      env:
        TOKEN: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
    - name: New tag version
      uses: ./.github/actions/git_tag_new_version
      id: bumVersion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Sync master branch with production branch
      if: always()
      uses: ./.github/actions/git_branch_sync_branches
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        from_branch: production
        to_branch: master
    - name: Delete Tag
      if: "cancelled() || failure()"
      run: |
        # The newly created tag is deleted if a step fails or the workflow is cancelled.
        git push --delete origin ${{ steps.bumVersion.outputs.new_tag}}
    - name: Notify by slack
      if: always()
      uses: ./.github/actions/slack_job_status
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: alerts
