# Lesli
# Copyright (c) 2023, Lesli Technologies, S. A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
#
# Lesli · Ruby on Rails SaaS Development Framework.
#
# Made with ♥ by https://www.lesli.tech
# Building a better future, one line of code at a time.
#
# @contact  hello@lesli.tech
# @website  https://www.lesli.dev
# @license  GPLv3 http://www.gnu.org/licenses/gpl-3.0.en.html
# // · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
# // · 



# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
# PLEASE DO NOT MODIFY THIS FILE ON THE CORE,
# THIS FILE SHOULD BE MODIFIED ON THE LesliTech/LesliActions REPOSITORY
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-



# Specs for Lesli Core
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
    name: "Static Analysis Security Tool"
    on:
      workflow_call: # This allows the workflow to be reusable
        inputs:
          branch:
            required: true
            type: string
    
    jobs:
      brakeman-scan:
        name: Static Analysis Security Tool
        runs-on: ubuntu-latest
    
        # Do not execute the test if requests comes from another action
        if: ${{ !contains(github.event.head_commit.message, 'ci(workflows):') && !contains(github.event.head_commit.message, 'release(gem):') && !contains(github.event.head_commit.message, 'assets(js):') }}

        steps:
    
          # Clone LesliBuilder repository
          - name: Checkout LesliBuilder repository
            uses: actions/checkout@v4
            with:
              repository: LesliTech/LesliBuilder
    
          # Clone engine repository
          - name: Checkout engine scode
            uses: actions/checkout@v4
            with:
              path: ./engines/${{ github.event.repository.name }}
              repository: LesliTech/${{ github.event.repository.name }}
    
          # Use the official receipt to install ruby in ubuntu
          - name: Install Ruby and gems
            uses: ruby/setup-ruby@v1
            with:
              ruby-version: 3.2.5
              bundler-cache: true
    
          # Run Brakeman
          - name: Run Brakeman Security Scanner
            run: |
              bundle exec brakeman 
              continue-on-error: true
    