name: Pull request master/production
on:
  pull_request:
    branches:
      - master
      - production
  workflow_dispatch:

jobs:
  test:
    name: Running RSpec Tests
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'release(gem):') && !contains(github.event.head_commit.message, 'assets(js):') && !contains(github.event.head_commit.message, 'ci(workflows):')"
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: leslicloud_test
          POSTGRES_DB: leslicloud_test
          POSTGRES_PASSWORD: "leslicloud_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout github actions repo
      uses: actions/checkout@v2
      with:
        repository: leitfaden/github_actions
        ref: production
        token: ${{ secrets.PUBLISH_GEM_BY_ACTIONS }}
        path: ./.github/
    - name: Notify slack github actions start 
      uses: ./.github/actions/slack_job_status
      with:
        job-status: INFO
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: alerts
        msg: Github actions start [ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ]
    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: ./Lesli/vendor/bundle
        key: ${{ runner.os }}-${{ github.event.repository.name }}-gems-${{ hashFiles('./Lesli/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.event.repository.name }}-gems-
    - name: Setting up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
      env:
        ImageOS: ubuntu20
    - name: Install dependencies of rails
      run: |
        bundle config https://rubygems.pkg.github.com/leitfaden ${GEM_HOST_API_KEY}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle list
      env:
        RAILS_ENV: test
        GEM_HOST_API_KEY: "ldonis:${{secrets.READ_GEM_BY_ACTIONS}}"
    - name: Setup test database
      run: |
        cp ./config/credentials/testci.yml.enc ./config/credentials/test.yml.enc
        bundle list
        bundle exec rake db:drop
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:setup
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.CORE_RAILS_MASTER_KEY_TEST }}
    - name: Run Spec tests
      run: |
        bundle exec rspec spec
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.CORE_RAILS_MASTER_KEY_TEST }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-lesli-core-${{ hashFiles('./package.json') }}
        restore-keys: |
          ${{ runner.os }}-lesli-core-
    - name: NPM install
      run: |
        npm install --prefix ./lib/vue3
    - name: Run Vue tests
      run: |
        npm run test
    - name: Notify by slack
      if: always()
      uses: ./.github/actions/slack_job_status
      with:
        job-status: ${{ job.status }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: alerts
